version: '3'
services:
  web:
    build: .
    volumes:
      - ".:/src"
    ports:
      - "4000:3000"
    links:
      - "db"

  db:
    image: postgres
    tmpfs:
      - /tmp
      - /var/run/postgresql
    volumes:
      - ./postgres-initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"